"use client";

import { useState } from "react";
import { FileDown, FileSpreadsheet } from "lucide-react";

function fmtRupiah(n: number) {
  return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(n);
}

export default function ExportButtons({ divisionId, period }: { divisionId?: string; period: string }) {
  const [loading, setLoading] = useState<"pdf" | "excel" | null>(null);

  async function fetchData() {
    const params = new URLSearchParams({ period });
    if (divisionId) params.set("divisionId", divisionId);
    const res = await fetch(`/api/keuangan/export?${params.toString()}`);
    return res.json();
  }

  async function exportExcel() {
    setLoading("excel");
    try {
      const XLSX = await import("xlsx");
      const data = await fetchData();

      const sheetRows = data.rows.map((r: any) => ({
        Tanggal: r.tanggal,
        Divisi: r.divisi,
        Tipe: r.tipe,
        Kategori: r.kategori,
        Deskripsi: r.deskripsi,
        Nominal: r.nominal,
      }));

      const ws = XLSX.utils.json_to_sheet(sheetRows);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Transaksi");
      XLSX.writeFile(wb, `Laporan-Keuangan-${data.title}-${period}.xlsx`);
    } finally {
      setLoading(null);
    }
  }

  async function exportPdf() {
    setLoading("pdf");
    try {
      const { default: jsPDF } = await import("jspdf");
      const autoTable = (await import("jspdf-autotable")).default;
      const data = await fetchData();

      const doc = new jsPDF();

      doc.setFontSize(16);
      doc.text("AKSARA MANAGEMENT SYSTEM", 14, 18);
      doc.setFontSize(11);
      doc.text(`Laporan Keuangan — ${data.title}`, 14, 26);
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Periode: ${data.period}`, 14, 32);

      autoTable(doc, {
        startY: 38,
        head: [["Tanggal", "Divisi", "Tipe", "Kategori", "Deskripsi", "Nominal"]],
        body: data.rows.map((r: any) => [
          r.tanggal,
          r.divisi,
          r.tipe,
          r.kategori,
          r.deskripsi,
          fmtRupiah(r.nominal),
        ]),
        styles: { fontSize: 8 },
        headStyles: { fillColor: [59, 99, 255] },
      });

      const finalY = (doc as any).lastAutoTable.finalY + 10;
      doc.setFontSize(10);
      doc.setTextColor(20);
      doc.text(`Total Pendapatan: ${fmtRupiah(data.summary.totalIncome)}`, 14, finalY);
      doc.text(`Total Pengeluaran: ${fmtRupiah(data.summary.totalExpense)}`, 14, finalY + 6);
      doc.text(`Laba Bersih: ${fmtRupiah(data.summary.netProfit)}`, 14, finalY + 12);

      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Generated by Aksara Management System — ${new Date().toLocaleDateString("id-ID")}`, 14, 285);

      doc.save(`Laporan-Keuangan-${data.title}-${period}.pdf`);
    } finally {
      setLoading(null);
    }
  }

  return (
    <div className="flex gap-2">
      <button
        onClick={exportExcel}
        disabled={loading !== null}
        className="inline-flex items-center gap-1.5 text-sm font-medium bg-white border border-slate-200 text-text px-3.5 py-2 rounded-xl hover:bg-slate-50 transition-colors disabled:opacity-50"
      >
        <FileSpreadsheet size={15} /> {loading === "excel" ? "Memproses..." : "Excel"}
      </button>
      <button
        onClick={exportPdf}
        disabled={loading !== null}
        className="inline-flex items-center gap-1.5 text-sm font-medium bg-white border border-slate-200 text-text px-3.5 py-2 rounded-xl hover:bg-slate-50 transition-colors disabled:opacity-50"
      >
        <FileDown size={15} /> {loading === "pdf" ? "Memproses..." : "PDF"}
      </button>
    </div>
  );
}
